### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1221328** [soarbear/Binance_triangle_arbitrage_bot#2]
Traceback (most recent call last):
  File "triangle_arbi.py", line 175, in <module>
    main()
  File "triangle_arbi.py", line 29, in main
    prices = get_prices(client)
  File "triangle_arbi.py", line 128, in get_prices
    prepared[primary][secondary] = 1/ask
ZeroDivisionError: float division by zero

**Comment by soarbear** [comment]
Rarely abnormal data such as zero or other unpredictable data be returned by binance server . so adding a filter may be good for you.

**Comment by GRTTX** [comment]
How do i add a filter can you please show an example
